name: altbn128

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/altbn128.yml"
      - "Dockerfile"
      - "**/*.cpp"
      - "**/*.hpp"
      - "**/*.asm"
      - "**/*.s"

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show runner CPU flags
        run: |
          uname -a
          lscpu || true
          grep -m1 -iE 'model name|flags' /proc/cpuinfo || true

      - name: Install deps
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
            build-essential nasm cmake git curl ca-certificates \
            libgmp-dev pkg-config nodejs npm

      - name: Build GoogleTest (static)
        run: |
          sudo apt-get install -y libgtest-dev
          sudo cmake -S /usr/src/googletest/googletest -B /tmp/gtest -DCMAKE_POSITION_INDEPENDENT_CODE=ON
          sudo cmake --build /tmp/gtest --parallel
          sudo cp /tmp/gtest/lib/*.a /usr/lib/

      - name: Generate fields (Fr, Fq)
        run: |
          npm i -g ffiasm
          buildzqfield -q 21888242871839275222246405745257275088548364400416034343698204186575808495617 -n Fr
          buildzqfield -q 21888242871839275222246405745257275088548364400416034343698204186575808495617 -n Fq
          ls -lah

      - name: Fetch test and helpers from iden3/ffiasm
        run: |
          git clone --depth 1 https://github.com/iden3/ffiasm.git ffiasm_up
          cp ffiasm_up/c/alt_bn128_test.cpp .
          # минимальный набор .cpp, который реально нужен
          cp ffiasm_up/c/alt_bn128.cpp ffiasm_up/c/naf.cpp ffiasm_up/c/splitparstr.cpp ffiasm_up/c/misc.cpp .

      - name: Assemble and build alt_bn128_test (no gtest_main!)
        run: |
          set -euxo pipefail
          nasm -felf64 fr.asm -o fr.o
          nasm -felf64 fq.asm -o fq.o
          # линковать только libgtest.a, т.к. в alt_bn128_test.cpp есть свой main
          g++ -std=c++17 -O3 \
             -I . -I ffiasm_up/c \
             fr.o fr.cpp fq.o fq.cpp \
             alt_bn128.cpp naf.cpp splitparstr.cpp misc.cpp \
             /usr/lib/libgtest.a -lgmp -pthread \
             alt_bn128_test.cpp \
             -o alt_bn128_test
          file ./alt_bn128_test
          ls -lah ./alt_bn128_test

      - name: Inspect generated ASM (check ADX/BMI2 usage)
        run: |
          objdump -d fr.o | egrep -n 'adcx|adox|mulx' || true
          objdump -d fq.o | egrep -n 'adcx|adox|mulx' || true

      - name: List tests (don’t fail pipeline if it crashes)
        continue-on-error: true
        env:
          GTEST_COLOR: "yes"
        run: |
          set -x
          timeout 5s ./alt_bn128_test --gtest_list_tests || echo "list_tests exit=$?"

      - name: Run a tiny shard (f2_simpleMul) with timeout
        env:
          GTEST_COLOR: "yes"
        run: |
          timeout 30s ./alt_bn128_test --gtest_filter=altBn128.f2_simpleMul

      - name: Upload artifacts (binary + objects)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: altbn128-build
          path: |
            alt_bn128_test
            fr.asm
            fq.asm
            fr.o
            fq.o
            *.cpp
