name: alt_bn128 tests (ffiasm)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show CPU flags (проверим ADX/BMI2)
        run: |
          grep -m1 -iE 'model name|flags' /proc/cpuinfo || true

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential nasm cmake git curl ca-certificates \
            libgmp-dev nodejs npm libgtest-dev

      - name: Build googletest (static)
        run: |
          cmake -S /usr/src/googletest/googletest -B /tmp/gtest -DCMAKE_POSITION_INDEPENDENT_CODE=ON
          cmake --build /tmp/gtest

      - name: Generate Fr/Fq via ffiasm
        run: |
          sudo npm i -g ffiasm
          buildzqfield -q 21888242871839275222246405745257275088548364400416034343698204186575808495617 -n Fr
          buildzqfield -q 21888242871839275222246405745257275088548364400416034343698204186575808495617 -n Fq
          ls -la

      - name: Fetch test sources from iden3/ffiasm
        run: |
          git clone --depth 1 https://github.com/iden3/ffiasm.git
          cp ffiasm/c/alt_bn128_test.cpp .

      - name: Assemble & link
        run: |
          nasm -felf64 fr.asm -o fr.o
          nasm -felf64 fq.asm -o fq.o

          # ВАЖНО: линкуем ТОЛЬКО libgtest.a (без gtest_main), т.к. alt_bn128_test.cpp содержит свой main
          g++ -std=c++17 -O3 -I . -I ffiasm/c \
            fr.o fr.cpp fq.o fq.cpp \
            ffiasm/c/alt_bn128.cpp ffiasm/c/naf.cpp ffiasm/c/splitparstr.cpp ffiasm/c/misc.cpp \
            /tmp/gtest/lib/libgtest.a -lgmp -pthread \
            alt_bn128_test.cpp -o alt_bn128_test

          file ./alt_bn128_test
          ldd  ./alt_bn128_test || true

      - name: Run tests
        run: |
          ./alt_bn128_test --gtest_color=yes --gtest_output=xml:test-report.xml

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: gtest-report
          path: test-report.xml
