name: ffiasm tests
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install -y build-essential nasm cmake libgmp-dev nodejs npm libgtest-dev
          cmake -S /usr/src/googletest/googletest -B /tmp/gtest -DCMAKE_POSITION_INDEPENDENT_CODE=ON
          sudo cmake --build /tmp/gtest
          sudo cp /tmp/gtest/lib/*.a /usr/lib/
          sudo npm i -g ffiasm
          buildzqfield -q 21888242871839275222246405745257275088548364400416034343698204186575808495617 -n Fr
          buildzqfield -q 21888242871839275222246405745257275088548364400416034343698204186575808495617 -n Fq
          git clone --depth 1 https://github.com/iden3/ffiasm.git
          cp ffiasm/c/alt_bn128_test.cpp .
          nasm -felf64 fr.asm -o fr.o
          nasm -felf64 fq.asm -o fq.o
          g++ -std=c++17 -O3 -I . -I ffiasm/c \
             fr.o fr.cpp fq.o fq.cpp \
             ffiasm/c/alt_bn128.cpp ffiasm/c/naf.cpp ffiasm/c/splitparstr.cpp ffiasm/c/misc.cpp \
             /usr/lib/libgtest.a /usr/lib/libgtest_main.a -lgmp -pthread \
             alt_bn128_test.cpp -o alt_bn128_test
          ./alt_bn128_test --gtest_color=yes
