name: ffiasm-smoke

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/ffiasm.yml"
      - "**/*.cpp"
      - "**/*.hpp"
      - "**/*.asm"

jobs:
  smoke:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
            build-essential nasm libgmp-dev nodejs npm

      - name: Gen + build minimal example
        run: |
          npm i -g ffiasm
          buildzqfield -q 21888242871839275222246405745257275088548364400416034343698204186575808495617 -n Fr
          cat > main.cpp << 'CPP'
          #include <stdio.h>
          #include <stdlib.h>
          #include "fr.hpp"
          int main() {
            Fr_init();
            FrElement a{.type=Fr_SHORT,.shortVal=2};
            FrElement b{.type=Fr_SHORT,.shortVal=6};
            FrElement c;
            Fr_mul(&c,&a,&b);
            char* s=Fr_element2str(&c);
            printf("%s\n", s);
            free(s);
            return 0;
          }
          CPP
          nasm -felf64 fr.asm -o fr.o
          g++ -std=c++17 -O3 main.cpp fr.o fr.cpp -lgmp -o example
          ./example | tee /tmp/out.txt
          grep -q "12" /tmp/out.txt

      - name: Inspect ADX
        run: |
          objdump -d fr.o | egrep -n 'adcx|adox|mulx' || true
