name: ffiasm tests
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential nasm cmake pkg-config libgmp-dev
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Sync upstream ffiasm tests
        run: |
          bash scripts/sync_ffiasm_tests.sh
        shell: bash

      - name: Generate BN254 fields (Fr/Fq)
        run: |
          npm i -g ffiasm
          Q=21888242871839275222246405745257275088548364400416034343698204186575808495617
          buildzqfield -q $Q -n Fr
          buildzqfield -q $Q -n Fq

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build -j

      - name: Test
        run: ctest --test-dir build --output-on-failure
