name: linux-fr-smoke
on:
  push:
  pull_request:

jobs:
  fr-smoke:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Deps
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm g++ libgmp-dev nodejs npm

      - name: Generate field
        run: |
          npm i -g ffiasm
          buildzqfield -q 21888242871839275222246405745257275088548364400416034343698204186575808495617 -n Fr
          ls -l

      - name: Build
        run: |
          nasm -felf64 fr.asm -o fr.o
          g++ -std=c++17 -O3 main.cpp fr.o fr.cpp -I . -lgmp -o fr_example
          objdump -d fr.o | egrep 'mulx|adcx|adox' || true
          grep -m1 -i 'flags' /proc/cpuinfo || true

      - name: Run
        run: |
          ./fr_example | tee out.txt
          grep -qx '12' out.txt

