name: linux-fr-smoke
on:
  push:
  pull_request:

jobs:
  fr-smoke:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Deps
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm g++ libgmp-dev nodejs npm

      - name: Generate field
        run: |
          npm i -g ffiasm
          buildzqfield -q 21888242871839275222246405745257275088548364400416034343698204186575808495617 -n Fr
          ls -l

      - name: Create main.cpp
        run: |
          cat > main.cpp <<'CPP'
          #include <gmp.h>
          #include "fr.hpp"
          #include <iostream>
          int main() {
            FrElement a, b, r;
            Fr_fromUI(&a, 2);
            Fr_fromUI(&b, 6);
            Fr_mul(&r, &a, &b);
            mpz_t z; mpz_init(z);
            Fr_toMpz(z, &r);
            char* s = mpz_get_str(nullptr, 10, z);
            std::cout << "Result: " << s << std::endl;
            free(s); mpz_clear(z);
            return 0;
         }
         CPP

      - name: Build
        run: |
          nasm -felf64 fr.asm -o fr.o
          g++ -std=c++17 -O3 main.cpp fr.o fr.cpp -I . -lgmp -o fr_example
          objdump -d fr.o | egrep 'mulx|adcx|adox' || true
          grep -m1 -i 'flags' /proc/cpuinfo || true

      - name: Run
        run: |
          ./fr_example | tee out.txt
          grep -qx '12' out.txt

